name: j3tunes
description: Music Streaming app made in Flutter!

publish_to: 'none'
version: 1.0.5

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0 <4.0.0'

dependencies:
  app_links: 
  audio_service: ^0.18.12
  audio_session: ^0.2.2
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  dynamic_color: 
  file_picker: ^10.3.3
  fluentui_system_icons: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  palette_generator: ^0.3.3
  flutter_flip_card: 
  flutter_localizations:
    sdk: flutter
  go_router: ^16.2.4
  hive: 
  hive_flutter: 
  html:
  http:
  intl:
  just_audio: ^0.10.5
  just_audio_background: ^0.0.1-beta.17
  rxdart: ^0.28.0
  url_launcher: 
  youtube_explode_dart:
    git:
      url: https://github.com/anandnet/youtube_explode_dart.git
  shared_preferences: 
  image_picker: 
  path_provider:
  dio: 
  get: 
  jiosaavn:  
  home_widget: ^0.8.0
  workmanager: ^0.9.0+3
  youtube_player_flutter: ^9.1.2
  shimmer: 
  lottie: 
  flutter_cache_manager:
  audio_video_progress_bar: 
  window_manager: ^0.5.1
  firebase_core: ^4.1.1
  firebase_analytics: ^12.0.2
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  google_sign_in: ^7.2.0
  font_awesome_flutter: 
  package_info_plus: ^9.0.0
  open_file: ^3.5.10 # Replaced open_file_plus
  permission_handler: ^12.0.1 # Added for storage permission
  share_plus: ^12.0.0
  device_apps_plus: 
  
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  translations_cleaner: 
  flutter_launcher_icons: ^0.14.4

dependency_overrides:
  collection: ^1.19.0

flutter:
  generate: true
  uses-material-design: true

 
  assets:
    - assets/licenses/
    - assets/images/
    - assets/animations/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf

flutter_icons:
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  image_path: "assets/images/JTunes.png"
  adaptive_icon_foreground: "assets/images/JTunes.png"
  adaptive_icon_background: "#FFFFFF"  # Default white
  adaptive_icon_monochrome: "assets/images/JTunes.png"  # For themed icons
  remove_alpha_ios: false
