name: j3tunes
description: Music Streaming app made in Flutter!

publish_to: 'none'
version: 1.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0 <4.0.0'

dependencies:
  app_links: 
  audio_service: ^0.18.12
  audio_session: 
  cached_network_image: ^3.3.1
  carousel_slider: ^5.1.1
  dynamic_color: 
  file_picker: 
  fluentui_system_icons: 
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_spinkit: ^5.2.0
  palette_generator: ^0.3.3
  flutter_flip_card: 
  flutter_localizations:
    sdk: flutter
  go_router: 
  hive: 
  hive_flutter: 
  html:
  http:
  intl:
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.17
  rxdart: 
  url_launcher: 
  youtube_explode_dart:
    git:
      url: https://github.com/anandnet/youtube_explode_dart.git
  shared_preferences: 
  image_picker: 
  path_provider:
  dio: 
  get: 
  jiosaavn:  
  home_widget: ^0.6.0
  workmanager: ^0.9.0+3
  youtube_player_flutter: 
  shimmer: 
  lottie: 
  flutter_cache_manager:
  audio_video_progress_bar: 
  window_manager: 
  firebase_core: ^2.32.0
  firebase_analytics: ^10.10.7
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.4
  google_sign_in: ^6.2.1
  font_awesome_flutter: 
  package_info_plus: 
  open_file_plus: ^3.4.1+1 # Added for APK installation
  permission_handler: ^11.3.1 # Added for storage permission
  share_plus:
  device_apps_plus: 
  google_mobile_ads: ^5.1.0 # Latest version check karein

  
  
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  translations_cleaner: 
  flutter_launcher_icons: ^0.13.1

dependency_overrides:
  collection: ^1.19.0

flutter:
  generate: true
  uses-material-design: true

 
  assets:
    - assets/licenses/
    - assets/images/
    - assets/animations/

  fonts:
    - family: paytoneOne
      fonts:
        - asset: fonts/paytone/PaytoneOne-Regular.ttf

flutter_icons:
  android: true
  ios: true
  macos:
    generate: true
  windows:
    generate: true
  image_path: "assets/images/JTunes.png"
  adaptive_icon_foreground: "assets/images/JTunes.png"
  adaptive_icon_background: "#FFFFFF"  # Default white
  adaptive_icon_monochrome: "assets/images/JTunes.png"  # For themed icons
  remove_alpha_ios: false
