// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSvydSUh9A-l5ROZTqp5xB104NtGUdi38',
    appId: '1:929077861289:android:963015ff3b42fc0c0682b8',
    messagingSenderId: '929077861289',
    projectId: 'jtunes-2eee8',
    storageBucket: 'jtunes-2eee8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD18mKqHZO2YcowNxxofKOvFfXzlCzttt4',
    appId: '1:929077861289:ios:c1b8e6ee7c76ce400682b8',
    messagingSenderId: '929077861289',
    projectId: 'jtunes-2eee8',
    storageBucket: 'jtunes-2eee8.firebasestorage.app',
    iosBundleId: 'com.jatin.j3tunes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD18mKqHZO2YcowNxxofKOvFfXzlCzttt4',
    appId: '1:929077861289:ios:c1b8e6ee7c76ce400682b8',
    messagingSenderId: '929077861289',
    projectId: 'jtunes-2eee8',
    storageBucket: 'jtunes-2eee8.firebasestorage.app',
    iosBundleId: 'com.jatin.j3tunes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBieecfNOxdgWzFa1mA7QZtJTGS52bmDMs',
    appId: '1:929077861289:web:3fd5e8c40be4f6aa0682b8',
    messagingSenderId: '929077861289',
    projectId: 'jtunes-2eee8',
    authDomain: 'jtunes-2eee8.firebaseapp.com',
    storageBucket: 'jtunes-2eee8.firebasestorage.app',
  );
}
